#!/usr/bin/env bash
UID_ROOT=0
OS=linux

cli_log() {
  script_name=${0##*/}

  timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  echo "$script_name@$timestamp >>  $1"
}

DN_LOG="/var/log/dreamnetwork-$(date +%Y%m%d_%H%M%S).log"

 normal=$(printf '\033[0m')
 bold=$(printf '\033[1m')
 faint=$(printf '\033[2m')
 underline=$(printf '\033[4m')
 negative=$(printf '\033[7m')
 red=$(printf '\033[31m')
 green=$(printf '\033[32m')
 orange=$(printf '\033[33m')
 blue=$(printf '\033[34m')
 yellow=$(printf '\033[93m')
 white=$(printf '\033[39m')


success ()
{
  local msg=${1}
  echo "[${bold}${green} OK ${normal}] ${msg}" | tee -a $DN_LOG
}

info ()
{
  local msg=${1}
  echo "[${bold}${blue}INFO${normal}] ${msg}" | tee -a $DN_LOG
}

warn ()
{
  local msg=${1}
  echo "[${bold}${orange}WARN${normal}] ${msg}" | tee -a $DN_LOG >&2
}

error ()
{
  local msg=${1}
  echo "[${bold}${red}FAIL${normal}] ${msg}" | tee -a $DN_LOG >&2
}

die () {
    error "$1"
    info "Logs are available in $DN_LOG"
    exit 1
}